### ISSUE TITLE
Support for WordPress Media / Default Gutenberg Classes.

### ISSUE THREAD

**Issue by adampatterson** [FullHuman/purgecss-with-wordpress#3]
Hey,

First. This works awesome for the most part out of the box but I did have issues with built-in WordPress media classes like `alignleft` `alignright` `aligncenter` and a few others.

Would you recommend adding Gutenberg to the `paths`?

**Comment by Ffloriel** [comment]
Hey,

I'm not really familiar with WordPress, to be honest. But I think those classes have been added with this PR: https://github.com/FullHuman/purgecss-with-wordpress/pull/2

**Comment by adampatterson** [comment]
Thanks!
